export const RouteLinks = [
  {
    name: 'Overview',
    icon: 'bi bi-speedometer2',
    route: '/overview',
    status: 'general',
    sub_routes: null,
  },
  {
    name: 'Messages',
    icon: 'bi bi-envelope',
    route: '/messages',
    status: 'general',
    sub_routes: null,
  },
  {
    name: 'Order List',
    icon: 'bi bi-geo-alt',
    route: '/order-list',
    status: 'seller',
  },
  {
    name: 'Orders',
    icon: 'bi bi-geo-alt',
    route: '/orders',
    status: 'buyer',
    sub_routes: null,
  },
  {
    name: 'Shipping Address',
    icon: 'bi bi-gift',
    route: '/manage-address',
    status: 'buyer',
    sub_routes: null,
  },
  {
    name: 'Inventory',
    icon: 'bi bi-gift',
    route: '/inventory',
    status: 'seller',
    sub_routes: null,
  },
  {
    name: 'Discount',
    icon: 'bi bi-percent',
    route: '/discount',
    status: 'seller',
    sub_routes: null,
  },
  {
    name: 'Profile',
    icon: 'bi bi-person',
    route: '/profile',
    status: 'seller',
    sub_routes: null,
  },
  {
    name: 'Reviews',
    icon: 'bi bi-pie-chart',
    route: '/review',
    status: 'buyer',
    sub_routes: null,
  },
  {
    name: 'Settings',
    icon: 'bi bi-gear',
    route: '/settings',
    status: 'general',
    sub_routes: null,
  },
  /* {
    name: 'Help',
    icon: 'bi bi-headset',
    route: '/help',
    status: 'seller',
    sub_routes: null,
  }, */
];
